# Generated by Django 3.2.4 on 2021-06-03 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('firstname', models.TextField(max_length=64, verbose_name='Имя')),
                ('lastname', models.TextField(max_length=64, verbose_name='Фамилия')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('amount', models.IntegerField(verbose_name='Сумма')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.user', verbose_name='Id пользователя')),
            ],
        ),
    ]
